"""Snapshot of the BrandMeister repeaters near home.

GENERATED by scripts/radios/build_brandmeister_snapshot.py - do not edit by hand.

Source: the BrandMeister network's public v2 API, https://api.brandmeister.network/v2, retrieved 2026-09-11:
device registry of the US masters 3102, 3103, 3104, each
repeater's static talkgroups, and the talkgroup directory. Repeaters within
100 miles of home seen in the last 60 days; positions are the
owners' own entries. Talkgroup usage: https://brandmeister.network/
"""
from __future__ import annotations

from typing import Dict, List, Tuple

from wasds150.models.catalog import FavoritesList

RETRIEVED = "2026-09-11"
RADIUS_MILES = 100

#: talkgroup id -> name (BrandMeister's directory, or the owning repeater)
TALKGROUPS: Dict[int, str] = {
    3153: 'Washington - 10 Minute Limit',
    30271: 'Canada BC 1',
    30272: 'Canada BC 2',
    31010: 'TG 31010',
    31412: 'Western Oregon',
    31531: 'Olympic Peninsula',
    31538: 'Washington State ARES',
    31539: 'Washington State ARES TAC',
    31771: 'PNWR',
    310186: 'K6MBY Local',
    311194: 'KF7CFR Local',
    311429: 'KC7Z Local',
    311757: 'N7QT Local',
    311886: 'TG 311886',
    312134: 'W7ECG Local',
    313153: 'TG 313153',
}

#: BrandMeister id, callsign, site, output MHz, input MHz, colour code, lat, lon,
#: last seen, ((static talkgroup, timeslot), ...)
REPEATERS: List[Tuple[int, str, str, float, float, int, float, float, str, Tuple[Tuple[int, int], ...]]] = [
    (312134, 'W7ECG', 'Ferndale, WA', 440.7375, 445.7375, 1, 48.86146, -122.61738, '2026-09-11', ((3153, 1), (31538, 1), (31771, 2), (311886, 2), (312134, 2))),
    (310186, 'K6MBY', 'Sequim,WA CN88kd', 440.7500, 445.7500, 1, 48.14580, -123.16430, '2026-09-11', ((31531, 1), (31538, 1), (3153, 2), (30271, 2), (30272, 2), (31010, 2), (310186, 2))),
    (315337, 'WA7JH-Gold-Silke', 'Gold Mt, Bremerton, Washington', 441.1750, 446.1750, 1, 47.54931, -122.78339, '2026-09-11', ((31412, 1), (31531, 1), (31538, 1), (311429, 2))),
    (311194, 'KF7CFR', 'Sedro-Woolley, WA', 441.9500, 446.9500, 1, 48.59475, -122.15945, '2026-09-07', ((3153, 1), (31538, 1), (31771, 2), (311194, 2))),
    (315345, 'KC7EQO', 'Sequim / Blyn', 442.1000, 447.1000, 1, 48.00670, -122.97266, '2026-09-11', ((31412, 1), (31531, 1), (31538, 1), (3153, 2), (311429, 2))),
    (311757, 'N7QT', 'Redmond', 442.3250, 447.3250, 1, 47.67460, -122.05393, '2026-09-11', ((31412, 1), (31538, 1), (31771, 1), (3153, 2), (31531, 2), (311429, 2), (311757, 2))),
    (313787, 'KC7Z Fox UHF', 'Bremerton - Fox13', 442.6500, 447.6500, 1, 47.54932, -122.78342, '2026-09-11', ((31412, 1), (31531, 1), (31538, 1), (31539, 2), (31771, 2), (311429, 2))),
    (312953, 'WA7EBH', 'Port Angeles, WA', 443.7000, 448.7000, 1, 48.05655, -123.32640, '2026-09-11', ()),
    (311439, 'W7JCR', 'Port Townsend', 443.8250, 448.8250, 1, 48.11628, -122.76453, '2026-09-11', ((313153, 1), (31531, 2), (31538, 2))),
    (311429, 'KC7Z-Cheryl', 'Bremerton - Cheryl St', 444.0750, 449.0750, 1, 47.60211, -122.61744, '2026-09-11', ((31412, 1), (31531, 1), (31538, 1), (31539, 2), (311429, 2))),
]


def favorites() -> List[FavoritesList]:
    """The BMNET list built from this snapshot."""
    from wasds150.catalog.brandmeister import favorites_from_snapshot

    return favorites_from_snapshot(TALKGROUPS, REPEATERS, RETRIEVED)


def favorite() -> FavoritesList:
    return favorites()[0]
