"""Verify the compliant lever can actually move.

Checks the things that would make a printed-in-place lever a solid lump
rather than a mechanism:

  1. Is the arm joined to the block ONLY at its flexure root?  The root is
     deliberately buried in the wall - that is the anchor.  But if the arm
     merges into surrounding material anywhere else along its length, it
     cannot rotate.

  2. Is the anchor actually the full size it should be?  A short slot of
     block behind the pivot leaves the root hanging partly in air, where
     it would tear away in use.

  3. Is there a printable gap around the rest of the moving part?

The probe includes the real variant file, so the wrapper's own overrides
apply.  Duplicating those values here would let the check drift away from
what actually gets printed.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/check_lever_free.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np
import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"
TMP = ROOT / ".tmp-cad"
OPENSCAD = Path(r"C:\Program Files\OpenSCAD\openscad.exe")

VARIANTS = ["lengthwise_lever", "crosswise_lever"]

# Flexure root dimensions, mirrored from sds150_mount_common.scad.
FLEX_ROOT = 3.0
FLEX_T = 1.3
ARM_W = 22.0
ANCHOR_VOLUME = FLEX_ROOT * FLEX_T * ARM_W

PROBE = """// generated by scripts/cad/check_lever_free.py
part = {part};
include <sds150_visor_mount_{variant}.scad>

// Suppress the wrapper's own assembly render.  OpenSCAD resolves each
// variable to its LAST assignment in the file, so this applies during the
// include above and leaves only the geometry below.
variant_render_mode = "none";

if (part == 0) {{
    difference() {{
        union() {{ visor_clamp(); block_solid(); }}
        block_cavities();
    }}
}} else {{
    socket_place() tongue();
}}
"""


def render(variant: str, part: int) -> trimesh.Trimesh:
    """Render either the block (part 0) or the moving arm (part 1)."""
    scad = MODELS / f".probe_{variant}_{part}.scad"
    out = TMP / f"probe_{variant}_{part}.stl"
    out.unlink(missing_ok=True)

    scad.write_text(PROBE.format(variant=variant, part=part), encoding="utf-8")
    try:
        result = subprocess.run(
            [str(OPENSCAD), "-o", str(out), str(scad)],
            capture_output=True, text=True,
        )
        if not out.exists() or out.stat().st_size < 200:
            for line in (result.stderr or "").strip().splitlines()[-6:]:
                print(f"    {line}")
            raise SystemExit(f"render failed: {variant} part {part}")
        return trimesh.load(out)
    finally:
        scad.unlink(missing_ok=True)


def main() -> None:
    TMP.mkdir(exist_ok=True)
    failures: list[str] = []

    for variant in VARIANTS:
        print(f"=== {variant} ===")
        block = render(variant, 0)
        arm = render(variant, 1)

        print(f"  block : {len(block.faces):5d} faces, "
              f"{block.volume / 1000:7.2f} cm^3, bodies={block.body_count}")
        print(f"  arm   : {len(arm.faces):5d} faces, "
              f"{arm.volume / 1000:7.2f} cm^3, bodies={arm.body_count}")

        try:
            shared = block.intersection(arm)
            overlap = float(shared.volume) if shared is not None else 0.0
        except Exception:  # noqa: BLE001 - engine may return empty
            shared, overlap = None, 0.0

        excess = overlap - ANCHOR_VOLUME
        print(f"  shared with block   = {overlap:8.2f} mm^3")
        print(f"  expected anchor     = {ANCHOR_VOLUME:8.2f} mm^3 "
              f"(flexure root buried in the wall)")
        print(f"  difference          = {excess:+8.2f} mm^3")

        if shared is not None and overlap > 0.1:
            lo, hi = shared.bounds
            print(f"  anchor spans  X {lo[0]:7.2f}..{hi[0]:7.2f}  "
                  f"Y {lo[1]:7.2f}..{hi[1]:7.2f}  "
                  f"Z {lo[2]:7.2f}..{hi[2]:7.2f}")

        sample = arm.sample(6000)
        _, distance, _ = trimesh.proximity.closest_point(block, sample)
        free = distance[distance > 0.001]
        if len(free):
            print(f"  clearance elsewhere = {free.min():8.3f} mm minimum, "
                  f"{np.percentile(free, 5):.3f} mm at 5th pct")

        if excess > 5.0:
            failures.append(
                f"{variant}: arm is fused to the block by {excess:.1f} mm^3 "
                "beyond its anchor - it cannot move"
            )
        elif excess < -5.0:
            failures.append(
                f"{variant}: anchor is {-excess:.1f} mm^3 short - the flexure "
                "root is not fully buried and would tear away"
            )
        print()

    if failures:
        print("FAILED:")
        for line in failures:
            print(f"  - {line}")
        sys.exit(1)

    print("lever is anchored correctly and free to move in both variants")


if __name__ == "__main__":
    main()
