"""Check the latch really can complete its stroke without binding.

WHY THIS EXISTS SEPARATELY FROM pd_fit_check.py
-----------------------------------------------
The fit checks ask "can the stud get in and out?".  They cannot answer
"can the latch move?", because the latch's relief and the latch itself are
generated from the SAME 2D outline.  Any error in the swept clearance
appears identically in both, so they still nest perfectly and every check
passes.

That is not hypothetical.  An earlier version sized the tooth relief using
the tooth's distance from the SLOT EDGE when rotation depends on distance
from the PIVOT - understating the sweep by half.  Every fit check passed.
The latch would have jammed part-way through its stroke on the real print.

So this script does something the model cannot do to itself: it renders
the body and the moving latch as separate solids, rotates the latch
through its full stroke in small steps, and measures the overlap at each
one.  The body never moves, so the two are compared against independent
geometry rather than against a shared assumption.

WHAT COUNTS AS A PASS
---------------------
The latch is anchored to the body by its flexure, so the two ALWAYS share
that ligament's volume - that is the joint, not a collision.  What must
not happen is the shared volume growing as the latch swings, which means
the two are grinding into each other somewhere else.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/check_pd_sweep.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"
TMP = ROOT / ".tmp-cad"

OPENSCAD_CANDIDATES = [
    Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
    Path("/usr/bin/openscad"),
    Path("/usr/local/bin/openscad"),
]

# Fractions of the full design stroke to test.  The end points matter
# least; binding usually starts part-way through, as the tooth swings
# along the slot rather than straight out of it.
FRACTIONS = [0.0, 0.25, 0.5, 0.75, 1.0]

# How much the overlap may grow over its resting value before it counts as
# interference rather than tessellation noise.
GROWTH_TOLERANCE = 1.30
ABSOLUTE_SLACK = 6.0     # mm^3

WRAPPER = """// generated by scripts/cad/check_pd_sweep.py - do not edit
include <sds150_pd_bracket.scad>
variant_render_mode = "none";
lever_pressed = false;
sweep_frac = {frac};

// Body never moves; the latch is swung through part of its stroke.
intersection() {{
    bracket_body();
    translate([pivot_x, pivot_y, 0])
        rotate([0, 0, -lever_angle * press_margin * sweep_frac])
            translate([-pivot_x, -pivot_y, 0])
                bracket_lever();
}}
"""


def find_openscad() -> Path:
    for path in OPENSCAD_CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("OpenSCAD not found - install it or edit OPENSCAD_CANDIDATES")


def overlap(openscad: Path, frac: float) -> float:
    """Volume shared by body and latch at this point in the stroke."""
    out = TMP / f"pdsweep-{frac:.2f}.stl"
    out.unlink(missing_ok=True)
    TMP.mkdir(exist_ok=True)

    scad = MODELS / f".pdsweep_{frac:.2f}.scad"
    scad.write_text(WRAPPER.format(frac=frac), encoding="utf-8")

    try:
        result = subprocess.run(
            [str(openscad), "-o", str(out), str(scad)],
            capture_output=True, text=True,
        )
    finally:
        scad.unlink(missing_ok=True)

    output = (result.stderr or "") + (result.stdout or "")

    if "Assertion" in output or "ERROR:" in output:
        for line in output.strip().splitlines()[-8:]:
            print(f"    {line}")
        raise SystemExit(f"OpenSCAD failed at stroke fraction {frac}")

    # An empty intersection would mean the latch had come completely
    # adrift from the body, which is its own kind of failure - but it is
    # caught by the body-count check, not here.
    if "top level object is empty" in output:
        return 0.0
    if not out.exists() or out.stat().st_size < 200:
        return 0.0

    return float(trimesh.load(out).volume)


def main() -> int:
    openscad = find_openscad()

    print("Peak Design bracket - latch stroke")
    print("-" * 58)
    print(f"  {'stroke':>8}  {'shared':>10}   note")

    vols = {}
    for frac in FRACTIONS:
        vol = overlap(openscad, frac)
        vols[frac] = vol
        note = "at rest - this is the flexure" if frac == 0 else ""
        print(f"  {100 * frac:6.0f} %  {vol:8.1f} mm^3   {note}")

    print("-" * 58)

    rest = vols[0.0]
    limit = rest * GROWTH_TOLERANCE + ABSOLUTE_SLACK

    worst_frac = max(vols, key=lambda f: vols[f])
    worst = vols[worst_frac]

    if rest <= 0.0:
        print("FAIL")
        print("  - the latch shares nothing with the body even at rest, so "
              "it is not attached: the flexure has been cut through")
        return 1

    if worst > limit:
        print("FAIL")
        print(f"  - shared volume grows from {rest:.1f} mm^3 at rest to "
              f"{worst:.1f} mm^3 at {100 * worst_frac:.0f}% of the stroke")
        print("  - the latch is grinding into the body rather than moving "
              "freely; the relief is not allowing for how far the lever "
              "swings ALONG the slot as it rotates")
        return 1

    print(f"PASS - shared volume stays within {limit:.1f} mm^3 throughout "
          f"the stroke,\n       so the latch pivots on its flexure without "
          "touching anything else")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
