"""Render the EFHW enclosure - body, lid and the two thread coupons.

Writes STL and 3MF into models/, then checks each result is a single
watertight solid before anything is sliced.

Both formats, from the same render.  STL is what every slicer reads; 3MF
carries its units explicitly, so a 128mm cylinder cannot arrive as a
128-inch one, and it is what the rest of this project ships.

Everything is exported in its own print orientation.  The body prints as
modelled, base down.  The lid is flipped by its own render mode - face
down on the plate - which puts the thread flanks the right way up to be
self-supporting and gives the lettering a glass-smooth face straight off
the build sheet.

The coupons are worth printing FIRST.  They are the real thread at the
real diameter, and they settle the fit in about twenty minutes instead of
a six-hour body print.  A thread coupon shrunk to some convenient smaller
size would prove nothing: the errors that bite scale with circumference.

Each part is checked for body_count as well as watertightness, and that
is not a formality.  The lid is a rim, a tube and a spigot; an early
version left the plug unattached to the rim and exported two perfectly
watertight solids with a 7mm gap between them - valid geometry that would
have arrived on the plate as two loose objects.

This takes a minute or two per render - the thread is a 180-segment sweep
and the lid carries text - and there are eight of them.  Long silent
stretches are normal.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/export_enclosure.py
"""

from __future__ import annotations

import subprocess
import time
from pathlib import Path

import numpy as np
import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"
TMP = ROOT / ".tmp-cad"

OPENSCAD_CANDIDATES = [
    Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
    Path("/usr/bin/openscad"),
    Path("/usr/local/bin/openscad"),
]

# The interior height the model is built at.  Named here only so the
# lid-invariance check below can render a second one to compare against;
# the model's own default is the single source of truth.
NOMINAL_H = 70.0   # mm, matching efhw_enclosure.scad
ALT_H = 80.0       # mm, used only to prove the lid does not care

# (render mode, file stem, parameter overrides).
#
# The overrides are the same mechanism the render mode uses: assignments
# placed AFTER the include, which OpenSCAD treats as overrides and feeds
# back into everything derived from them.
#
# One body, one lid.  The interior height is a parameter of the model
# rather than a variant here - changing it is a one-line edit that
# re-derives the whole stack, and shipping two bodies that differ only in
# height is a good way to print the wrong one.
EXPORTS = [
    ("body",        "efhw_enclosure_body", {}),
    ("lid",         "efhw_enclosure_lid",  {}),
    ("coupon_body", "efhw_coupon_body",    {}),
    ("coupon_lid",  "efhw_coupon_lid",     {}),
]

# Both formats, from the same render.
#
# STL is what every slicer reads.  3MF carries units explicitly, so a
# 128mm cylinder cannot arrive as a 128-inch one, and it is what the rest
# of this project ships alongside its STLs.
FORMATS = ["stl", "3mf"]

# The assignment comes AFTER the include, which is what makes it an
# override rather than a duplicate - the values derived inside the model
# are recomputed from it.  Verified before being relied on; it does not
# work this way for `use <>`.
WRAPPER = """// generated by scripts/cad/export_enclosure.py - do not edit
include <efhw_enclosure.scad>
variant_render_mode = "{mode}";
"""


def find_openscad() -> Path:
    for path in OPENSCAD_CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("OpenSCAD not found - install it or edit OPENSCAD_CANDIDATES")


def render(openscad: Path, mode: str, out: Path,
           overrides: dict | None = None) -> float:
    extra = "".join(f"{k} = {v};\n" for k, v in (overrides or {}).items())
    tag = "_".join(f"{k}{v:g}" for k, v in (overrides or {}).items())
    tmp = MODELS / f".export_efhw_{mode}{tag}_{out.suffix.lstrip('.')}.scad"
    tmp.write_text(WRAPPER.format(mode=mode) + extra, encoding="utf-8")
    out.unlink(missing_ok=True)
    started = time.monotonic()
    try:
        result = subprocess.run(
            [str(openscad), "-o", str(out), str(tmp)],
            capture_output=True,
            text=True,
        )
    finally:
        tmp.unlink(missing_ok=True)

    # An empty result and a crashed render leave the same thing behind -
    # nothing - so both are caught here rather than surfacing later as a
    # confusing trimesh error about a file with no triangles in it.
    if not out.exists() or out.stat().st_size < 200:
        print((result.stderr or "")[-2000:])
        raise SystemExit(f"OpenSCAD produced nothing for {out.name}")

    return time.monotonic() - started


def check(path: Path, secs: float) -> bool:
    mesh = trimesh.load(path)
    ok = mesh.is_watertight and mesh.body_count == 1

    # body_count is not a formality here.  The lid is a rim, a tube and a
    # spigot; an early version left the plug unattached to the rim and
    # exported two perfectly watertight solids with a 7mm gap between
    # them, which would have arrived on the plate as two loose objects.
    note = "ok"
    if not mesh.is_watertight:
        note = "NOT WATERTIGHT"
    elif mesh.body_count != 1:
        note = f"{mesh.body_count} SEPARATE BODIES - not one part"

    size = mesh.bounds[1] - mesh.bounds[0]
    print(f"  {path.name:<32} {mesh.volume / 1000:6.1f} cm^3  "
          f"{size[0]:5.1f} x {size[1]:5.1f} x {size[2]:5.1f} mm  "
          f"{secs:4.0f}s  {note}")
    return ok


def check_lid_same(openscad: Path) -> bool:
    """Prove the lid does not care how tall the body is.

    Every z in the lid is measured from the rim, so changing the interior
    height should slide the whole lid up or down without altering its
    shape - which is why only one lid is exported, and why the interior
    height can be re-tuned later without reprinting it.

    That reasoning is sound and it is also exactly the kind of thing this
    project has got wrong before, quietly, by arguing from the code rather
    than measuring the result.  So it is measured: render the lid at two
    heights, move each to the origin, and compare.  If they ever differ,
    the lid has picked up a dependency on the body's length and shipping
    one lid would be an error nobody would notice until two printed parts
    refused to meet.
    """
    meshes = []
    for h in (NOMINAL_H, ALT_H):
        out = TMP / f"lid_check_h{h:.0f}.stl"
        render(openscad, "lid", out, {"interior_h": h})
        m = trimesh.load(out)
        m.apply_translation(-m.bounds[0])
        meshes.append(m)

    a, b = meshes
    d_vol = abs(a.volume - b.volume)
    d_box = float(np.abs((a.bounds[1] - a.bounds[0])
                         - (b.bounds[1] - b.bounds[0])).max())

    same = d_vol < 1.0 and d_box < 0.01
    print(f"  lid at {NOMINAL_H:.0f}mm vs {ALT_H:.0f}mm interior: "
          f"volume differs by {d_vol:.3f} mm^3, "
          f"bounding box by {d_box:.4f} mm  "
          f"{'- identical, the lid is height-independent' if same else '- DIFFERENT'}")
    return same


def main() -> int:
    openscad = find_openscad()
    TMP.mkdir(exist_ok=True)
    bad: list[str] = []

    print("EFHW enclosure")
    for mode, stem, overrides in EXPORTS:
        for ext in FORMATS:
            out = MODELS / f"{stem}.{ext}"
            secs = render(openscad, mode, out, overrides)

            # Only the STL is inspected.  trimesh reads both, but the
            # geometry is identical by construction - they come from the
            # same render - so checking twice would just double a slow
            # test to say the same thing.
            if ext == "stl":
                if not check(out, secs):
                    bad.append(out.name)
            else:
                print(f"  {out.name:<32} {'':>6}       "
                      f"{'':>21}  {secs:4.0f}s  written")

    print()
    if not check_lid_same(openscad):
        bad.append("the lid is not the same at both interior heights")

    print()
    if bad:
        print("these are not right:")
        for name in bad:
            print(f"  - {name}")
        return 1

    print("all exports are single watertight solids")
    print("the lid is modelled in place and flipped for printing, so it "
          "exports face down")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
