"""Render the Peak Design bracket in each tripod socket style.

Writes STL and 3MF into models/, then checks each result is a single
watertight solid.

The bracket is modelled already print-oriented - bearing face down on the
build plate - so nothing is rotated here.  That orientation is what makes
the latch printable in place: it flexes sideways, in the layer plane, and
the slots it moves in are vertical.  Laid any other way the slicer would
want support inside those slots, which would weld the mechanism solid.

There is no test coupon.  The mechanism spans the whole plate, so every
trim that saved worthwhile material either cut through it or sliced a
corner fillet into a feather edge; the ones that kept the walls sound
removed 5%.  The full bracket is cheap enough to print and check directly.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/export_pd_bracket.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"

OPENSCAD_CANDIDATES = [
    Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
    Path("/usr/bin/openscad"),
    Path("/usr/local/bin/openscad"),
]

# How the 1/4"-20 tripod socket is made.  self_tap is the default and the
# one to print first: the steel screw cuts a full-depth thread, which
# holds better than a printed one and needs no hardware.
#
# There is no modelled-helix option: at a 0.4mm nozzle its crests come to
# a knife edge, so it prints mushy and holds worse than self-tapping.
STYLES = ["self_tap", "insert", "nut"]

WRAPPER = """// generated by scripts/cad/export_pd_bracket.py - do not edit
include <sds150_pd_bracket.scad>
variant_render_mode = "{mode}";
thread_style = "{style}";
"""


def find_openscad() -> Path:
    for path in OPENSCAD_CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("OpenSCAD not found - install it or edit OPENSCAD_CANDIDATES")


def render(openscad: Path, mode: str, style: str, out: Path) -> None:
    tmp = MODELS / f".export_pd_{mode}_{style}.scad"
    tmp.write_text(WRAPPER.format(mode=mode, style=style), encoding="utf-8")
    out.unlink(missing_ok=True)
    try:
        result = subprocess.run(
            [str(openscad), "-o", str(out), str(tmp)],
            capture_output=True,
            text=True,
        )
    finally:
        tmp.unlink(missing_ok=True)

    if not out.exists() or out.stat().st_size < 200:
        print((result.stderr or "")[-2000:])
        raise SystemExit(f"OpenSCAD produced nothing for {out.name}")


def check(path: Path) -> bool:
    mesh = trimesh.load(path)
    ok = mesh.is_watertight and mesh.body_count == 1

    size = mesh.bounds[1] - mesh.bounds[0]
    print(f"  {path.name:<42} {mesh.volume / 1000:6.2f} cm^3  "
          f"{size[0]:5.1f} x {size[1]:5.1f} x {size[2]:5.1f} mm  "
          f"{'ok' if ok else 'NOT A SINGLE WATERTIGHT SOLID'}")
    return ok


def main() -> int:
    openscad = find_openscad()
    all_ok = True

    print("Peak Design bracket")
    for style in STYLES:
        stem = f"sds150_pd_bracket_{style}"
        for ext in ("stl", "3mf"):
            out = MODELS / f"{stem}.{ext}"
            render(openscad, "assembly", style, out)
        all_ok &= check(MODELS / f"{stem}.stl")

    if not all_ok:
        print("\nsome exports are not clean solids")
        return 1

    print("\nall exports are single watertight solids")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
