"""Render the SDS150 visor mount variants and their fit-test coupons.

Writes STL and 3MF into models/, then checks each result is a single
watertight solid.

Coupons are produced by generating a throwaway wrapper that selects the
"coupon" render mode, because OpenSCAD's -D only overrides variables that
are already declared in the root file.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/export_models.py
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"

OPENSCAD_CANDIDATES = [
    Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
    Path("/usr/bin/openscad"),
    Path("/usr/local/bin/openscad"),
]

VARIANTS = [
    "lengthwise",
    "crosswise",
    "lengthwise_lever",
    "crosswise_lever",
]

WRAPPER = """// generated by scripts/cad/export_models.py - do not edit
include <sds150_visor_mount_{axis}.scad>
variant_render_mode = "{mode}";
"""


def find_openscad() -> Path:
    for path in OPENSCAD_CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("OpenSCAD not found - install it or edit OPENSCAD_CANDIDATES")


def render(openscad: Path, source: Path, out: Path) -> None:
    """Render one file.  The model already emits itself print-oriented."""
    out.unlink(missing_ok=True)
    result = subprocess.run(
        [str(openscad), "-o", str(out), str(source)],
        capture_output=True,
        text=True,
    )
    if not out.exists() or out.stat().st_size < 200:
        print((result.stderr or "")[-2000:])
        raise SystemExit(f"OpenSCAD produced nothing for {out.name}")


def render_mode(openscad: Path, axis: str, mode: str, out: Path) -> None:
    """Render a variant in a specific mode via a temporary wrapper."""
    tmp = MODELS / f".export_{axis}_{mode}.scad"
    tmp.write_text(WRAPPER.format(axis=axis, mode=mode), encoding="utf-8")
    try:
        render(openscad, tmp, out)
    finally:
        tmp.unlink(missing_ok=True)


def verify(path: Path) -> bool:
    mesh = trimesh.load(path)
    size = mesh.bounds[1] - mesh.bounds[0]
    ok = mesh.is_watertight and mesh.body_count == 1
    print(
        f"  [{'ok ' if ok else 'BAD'}] {path.name:38s} "
        f"{size[0]:6.1f} x {size[1]:6.1f} x {size[2]:6.1f} mm   "
        f"{mesh.volume / 1000:6.2f} cm^3   "
        f"watertight={mesh.is_watertight} bodies={mesh.body_count}"
    )
    return ok


def main() -> None:
    openscad = find_openscad()
    all_ok = True

    for variant in VARIANTS:
        source = MODELS / f"sds150_visor_mount_{variant}.scad"
        print(f"=== {variant} ===")

        stl = MODELS / f"sds150_visor_mount_{variant}.stl"
        render(openscad, source, stl)
        all_ok &= verify(stl)

        threemf = MODELS / f"sds150_visor_mount_{variant}.3mf"
        render(openscad, source, threemf)
        print(f"  [ok ] {threemf.name}")

        coupon = MODELS / f"coupon_{variant}.stl"
        render_mode(openscad, variant, "coupon", coupon)
        all_ok &= verify(coupon)
        print()

    if not all_ok:
        print("one or more exports are not a single watertight solid")
        sys.exit(1)

    print("all exports written and verified")


if __name__ == "__main__":
    main()
