"""Verify the SDS150 socket actually captures the stud.

Renders models/fit_check.scad in several poses and measures the volume of
material the stud would collide with, which tells us whether the latch
behaves as designed:

  seated  - stud parked in the locked position.  Nothing should touch, so
            this must be ~0.
  slide   - stud swept from the entry hole to the lock.  The only thing in
            the way should be the detent bump.
  drop    - stud dropping in through the entry hole.  Same expectation.
  escape  - stud pulled straight out while locked.  This must be heavily
            blocked by the ledge; a large volume here is the pass.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/fit_check.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"
TMP = ROOT / ".tmp-cad"

OPENSCAD_CANDIDATES = [
    Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
    Path("/usr/bin/openscad"),
    Path("/usr/local/bin/openscad"),
]

# Every printable variant, by the name of its .scad file.
VARIANTS = [
    "lengthwise",
    "crosswise",
    "lengthwise_lever",
    "crosswise_lever",
]

CHECKS = {
    "seated": 0,
    "slide": 1,
    "drop": 2,
    "escape": 3,
    "stud": 4,
    "ledge": 6,
    "disc": 7,
}

# Include the real variant file, then suppress its own assembly render and
# draw the check geometry instead.  OpenSCAD resolves each variable to its
# LAST assignment, so variant_render_mode applies during the include.
# Duplicating the variant settings here would let the checks drift away
# from what actually gets printed - which has happened before.
WRAPPER = """// generated by scripts/cad/fit_check.py - do not edit
check_id = {check_id};
include <sds150_visor_mount_{variant}.scad>
variant_render_mode = "none";
include <fit_check.scad>
"""


def find_openscad() -> Path:
    for path in OPENSCAD_CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("OpenSCAD not found - install it or edit OPENSCAD_CANDIDATES")


def render(openscad: Path, variant: str, check: str) -> float:
    """Render one test pose and return its volume; 0.0 when empty."""
    out = TMP / f"fit-{variant}-{check}.stl"
    out.unlink(missing_ok=True)

    scad = MODELS / f".fit_{variant}_{check}.scad"
    scad.write_text(
        WRAPPER.format(variant=variant, check_id=CHECKS[check]),
        encoding="utf-8",
    )

    try:
        result = subprocess.run(
            [str(openscad), "-o", str(out), str(scad)],
            capture_output=True, text=True,
        )
    finally:
        scad.unlink(missing_ok=True)

    output = (result.stderr or "") + (result.stdout or "")

    # OpenSCAD exits non-zero on an empty result, which for most of these
    # poses is a pass rather than a failure.  An assertion failure is not.
    if "Assertion" in output or "ERROR:" in output:
        for line in output.strip().splitlines()[-8:]:
            print(f"    {line}")
        raise SystemExit(f"OpenSCAD failed for {variant}/{check}")

    if "top level object is empty" in output:
        return 0.0

    if not out.exists() or out.stat().st_size < 200:
        return 0.0
    return float(trimesh.load(out).volume)


def main() -> None:
    openscad = find_openscad()
    TMP.mkdir(exist_ok=True)

    failures: list[str] = []

    for axis in VARIANTS:
        print(f"=== {axis} ===")
        volumes = {name: render(openscad, axis, name) for name in CHECKS}
        reference = volumes["stud"]
        print(f"  stud volume         = {reference:8.1f} mm^3")
        for name in ("seated", "slide", "drop", "escape"):
            share = 100 * volumes[name] / reference if reference else 0
            print(f"  {name:8s} obstruction = {volumes[name]:8.1f} mm^3  ({share:5.1f}% of stud)")

        # How much roof actually sits over the locked head, measured
        # against the most any keyhole could have (the head's footprint
        # minus the neck slot that must pass through the ledge).  A short
        # slot leaves the head partly under the open entry hole, which
        # shows up here as missing ledge.
        disc = volumes["disc"]
        cover = 100 * volumes["ledge"] / disc if disc else 0
        print(f"  ledge over head     = {volumes['ledge']:8.1f} mm^3  "
              f"({cover:5.1f}% of the most a keyhole could have)")

        if reference < 100:
            failures.append(f"{axis}: stud reference volume looks wrong")
            continue

        if volumes["seated"] > 0.02 * reference:
            failures.append(f"{axis}: stud fouls the socket when locked")

        # Getting in must be possible - only the detent should resist.
        # The bump's own volume is the yardstick, not the stud's: a longer
        # slot does not mean a bigger obstruction, so the threshold must
        # not scale with travel.
        for name in ("slide", "drop"):
            if volumes[name] > 0.35 * reference:
                failures.append(
                    f"{axis}: {name} path is obstructed by "
                    f"{volumes[name]:.0f} mm^3 - more than the detent alone"
                )

        if volumes["escape"] < 0.15 * reference:
            failures.append(f"{axis}: locked stud is NOT captive")

        if volumes["slide"] < 1.0:
            failures.append(f"{axis}: detent bump does not engage the stud")

        if cover < 90:
            failures.append(
                f"{axis}: only {cover:.0f}% of the head is covered by ledge - "
                "slot_travel is too short, the head can lift into the entry hole"
            )

        print()

    if failures:
        print("FAILED:")
        for line in failures:
            print(f"  - {line}")
        sys.exit(1)

    print("all fit checks passed")


if __name__ == "__main__":
    main()
