"""Verify the Peak Design bracket actually captures - and releases - the stud.

Renders models/pd_fit_check.scad in several poses and measures the volume
of material the stud would collide with.  Volume is a blunt instrument but
an honest one: it cannot be talked into agreeing with the design.

The pair that matters most is `rise` and `released`.  `rise` proves the
latch blocks the stud from going back up to the entry hole; `released`
re-runs the same motion with the latch deflected as a thumb would deflect
it, and must come out clear.  Together they show the latch is both the
reason the radio stays on and the only thing stopping it coming off - so
pressing the tab genuinely frees it, rather than merely looking as though
it should.

Usage:
    .venv-cad/Scripts/python.exe scripts/cad/pd_fit_check.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import trimesh

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "models"
TMP = ROOT / ".tmp-cad"

OPENSCAD_CANDIDATES = [
    Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
    Path("/usr/bin/openscad"),
    Path("/usr/local/bin/openscad"),
]

# check name -> (check_id, press the latch?)
CHECKS = {
    "seated": (0, False),
    "slide": (1, False),
    "drop": (2, False),
    "escape": (3, False),
    "rise": (4, False),
    "released": (5, True),
    "ledge": (6, False),
    "disc": (7, False),
    "clash_rest": (8, False),
    "clash": (8, True),
}

# Include the real bracket, silence its own render, then draw the check
# geometry.  OpenSCAD resolves each variable to its LAST assignment, so
# the settings below apply during the include.  Do not restate any of the
# bracket's numbers here - stale duplicates in check scripts caused three
# false failures while the visor mount was being developed.
#
# lever_pressed is a boolean, not an angle, because a wrapper cannot refer
# to values computed inside the file it includes: writing the deflection
# as `lever_angle` here silently yielded undef and left the latch at rest,
# so the release check passed on geometry it had never actually moved.
WRAPPER = """// generated by scripts/cad/pd_fit_check.py - do not edit
check_id = {check_id};
include <sds150_pd_bracket.scad>
variant_render_mode = "none";
lever_pressed = {press};
include <pd_fit_check.scad>
"""


def find_openscad() -> Path:
    for path in OPENSCAD_CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("OpenSCAD not found - install it or edit OPENSCAD_CANDIDATES")


def render(openscad: Path, check: str) -> float:
    """Render one pose and return its volume in mm^3; 0.0 when empty."""
    check_id, press = CHECKS[check]

    out = TMP / f"pdfit-{check}.stl"
    out.unlink(missing_ok=True)
    TMP.mkdir(exist_ok=True)

    scad = MODELS / f".pdfit_{check}.scad"
    scad.write_text(
        WRAPPER.format(
            check_id=check_id,
            press="true" if press else "false",
        ),
        encoding="utf-8",
    )

    try:
        result = subprocess.run(
            [str(openscad), "-o", str(out), str(scad)],
            capture_output=True,
            text=True,
        )
    finally:
        scad.unlink(missing_ok=True)

    output = (result.stderr or "") + (result.stdout or "")

    # OpenSCAD exits non-zero when the result is empty, which for several
    # of these poses is exactly the pass condition - so the exit code
    # cannot be trusted on its own.  A genuine error still must not pass
    # silently.
    if "Assertion" in output or "ERROR:" in output:
        for line in output.strip().splitlines()[-8:]:
            print(f"    {line}")
        raise SystemExit(f"OpenSCAD failed rendering '{check}'")

    # An empty result is legitimate, but ONLY when OpenSCAD says so.
    if "top level object is empty" in output:
        return 0.0

    # Anything else that produced no usable file is a failure of this
    # script, not a measurement of zero.  Returning 0.0 here would be
    # indistinguishable from a real empty intersection - which is exactly
    # how a stale file lock once made the resting overlap read as 0.0 and
    # turned a passing design into a spurious "binding" failure.
    if not out.exists():
        raise SystemExit(
            f"'{check}' produced no STL and OpenSCAD did not report an "
            f"empty result - the render did not complete.\n"
            f"    (a leftover openscad.exe holding {out.name} will do this)"
        )

    if out.stat().st_size < 200:
        raise SystemExit(
            f"'{check}' wrote a truncated STL ({out.stat().st_size} bytes)"
        )

    mesh = trimesh.load(out)
    return float(mesh.volume)


def main() -> int:
    openscad = find_openscad()

    vols = {name: render(openscad, name) for name in CHECKS}

    coverage = (
        100.0 * vols["ledge"] / vols["disc"] if vols["disc"] > 0 else 0.0
    )

    print("Peak Design bracket - stud fit")
    print("-" * 58)
    for name in CHECKS:
        print(f"  {name:<10} {vols[name]:9.1f} mm^3")
    print(f"  {'coverage':<10} {coverage:9.1f} %")
    print("-" * 58)

    failures: list[str] = []

    # Assembly must not be a press fit; the ledge preload is applied by
    # the stud head against the pedestal, not by squeezing the stud.
    if vols["seated"] > 5.0:
        failures.append(
            f"seated: {vols['seated']:.1f} mm^3 of interference in the "
            "locked position - the stud will not sit down"
        )

    if vols["drop"] > 5.0:
        failures.append(
            f"drop: entry hole is obstructed by {vols['drop']:.1f} mm^3 - "
            "the head will not pass through"
        )

    # The latch has to be in the way going in, or it is not a latch.  But
    # only a little: the neck must be able to shove it aside.
    if vols["slide"] < 1.0:
        failures.append(
            "slide: nothing obstructs the stud on the way in, so the "
            "latch tooth is not reaching into the slot at all"
        )
    if vols["slide"] > 120.0:
        failures.append(
            f"slide: {vols['slide']:.1f} mm^3 in the way - far more than "
            "the tooth alone, so something else is fouling the path"
        )

    if vols["rise"] < 1.0:
        failures.append(
            "rise: the stud can travel back to the entry hole unimpeded - "
            "the latch does not block it"
        )

    # The whole point of the mount.
    if vols["escape"] < 200.0:
        failures.append(
            f"escape: only {vols['escape']:.1f} mm^3 resists pulling the "
            "stud straight out - the ledge is not holding it"
        )

    # And the whole point of the latch being a lever.
    # Guard against the press silently not happening.  If deflecting the
    # latch changes nothing at all, the release checks below are measuring
    # the resting geometry and would pass or fail for the wrong reasons -
    # which is exactly what happened when the deflection was passed in a
    # form OpenSCAD quietly evaluated to undef.
    if abs(vols["rise"] - vols["released"]) < 1e-6 and vols["rise"] > 0:
        failures.append(
            "the latch did not move when pressed - the release checks are "
            "measuring the resting geometry, so their result means nothing"
        )

    if vols["released"] > 5.0:
        failures.append(
            f"released: {vols['released']:.1f} mm^3 still blocks the stud "
            "with the latch fully pressed - it cannot be taken off"
        )

    if coverage < 90.0:
        failures.append(
            f"coverage: ledge covers only {coverage:.1f}% of the head, so "
            "it could tilt and work free"
        )

    # Coverage above 100% means the measurement and its reference have
    # drifted apart - the ratio is of a fixed ledge against the most a
    # keyhole could possibly cover, so it cannot legitimately exceed 1.
    # It read 101.1% once, when the latch tooth was being counted as
    # ledge; the number looked healthy and was meaningless.
    if coverage > 100.5:
        failures.append(
            f"coverage: {coverage:.1f}% is above the theoretical maximum, "
            "so the ledge check is measuring something its reference does "
            "not account for - the figure cannot be trusted"
        )

    # At rest the latch touches the body only through its flexure.  When
    # pressed it must still touch only through the flexure; anything more
    # means it is binding on the plate.  The resting overlap is measured
    # rather than computed, so this check cannot drift out of step with
    # the model the way a hard-coded figure would.
    if vols["clash"] > vols["clash_rest"] * 1.35 + 5.0:
        failures.append(
            f"clash: latch shares {vols['clash']:.1f} mm^3 with the body "
            f"when pressed, against {vols['clash_rest']:.1f} mm^3 at rest "
            "- it is binding on the plate rather than flexing freely"
        )

    if failures:
        print("FAIL")
        for line in failures:
            print(f"  - {line}")
        return 1

    print("PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
