"""Machine-generated Markdown summary of the generated Favorites List set.

This is a *generated overview*, not a replacement for the hand-curated
``washington-sds150-favorites-master.md`` — it exists so an exported bundle
is self-contained/readable without also shipping the full narrative guide,
and is clearly labeled as machine-generated to avoid any confusion with the
human-authored reference.
"""
from __future__ import annotations

import datetime
from pathlib import Path
from typing import List, Optional

from wasds150.models.catalog import FavoritesList
from wasds150.bundle.validation import validate_markdown_bytes

_COLUMNS = (
    ("favorite_key", "Key"),
    ("favorite_name", "Name"),
    ("region", "Region"),
    ("scenario", "Scenario"),
    ("mode", "Mode"),
    ("monitorability", "Monitorability"),
)


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").replace("\r", "")


def render_markdown(favorites: List[FavoritesList], *, generated_at: Optional[str] = None) -> str:
    generated_at = generated_at or datetime.datetime.now(datetime.timezone.utc).isoformat()
    lines: List[str] = []
    lines.append("# Generated Favorites List Overview")
    lines.append("")
    lines.append(
        "_Machine-generated by wasds150 — not a substitute for "
        "`washington-sds150-favorites-master.md`, the hand-curated reference._"
    )
    lines.append("")
    lines.append(f"Generated: {generated_at}")
    lines.append(f"Total lists: {len(favorites)}")
    lines.append("")
    header = "| " + " | ".join(label for _, label in _COLUMNS) + " |"
    sep = "|" + "|".join(["---"] * len(_COLUMNS)) + "|"
    lines.append(header)
    lines.append(sep)
    for fl in favorites:
        row = " | ".join(_escape(getattr(fl, field_name)) for field_name, _ in _COLUMNS)
        lines.append(f"| {row} |")
    lines.append("")
    return "\n".join(lines)


def export_markdown(favorites: List[FavoritesList], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(favorites), encoding="utf-8")
    validate_markdown_bytes(path.read_bytes(), favorites)
    return path
