"""Regenerate ``src/wasds150/catalog/atd890_dmr.py`` from the SeattleDMR
Config Builder files.

Usage (from the repository root, with the local catalog present so repeater
coordinates can be joined from the WWARA rows)::

    .venv\\Scripts\\python.exe scripts\\radios\\build_atd890_dmr_snapshot.py [--from DIR]

Without ``--from`` the three files are downloaded from
https://seattledmr.com/ConfigBuilder/. The generated module embeds only the
parsed Washington repeaters, their talkgroup/timeslot layout, the talkgroup
ids and the Seattle ACS analog channels, with the source URLs, retrieval date
and SHA-256 of each input recorded at the top.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from wasds150.models.catalog import Catalog  # noqa: E402
from wasds150.recipes.dmr_networks import coordinate_lookup_from_catalog  # noqa: E402
from wasds150.sources.k7abd import (  # noqa: E402
    SEATTLEDMR_FILES,
    RepeaterDef,
    parse_analog,
    parse_digital_repeaters,
    parse_talkgroups,
    site_tokens,
)

#: Repeaters the network's own pages list that the Config Builder file does
#: not carry yet. SeattleDMR "Seattle East" (K7NWS, West Tiger Mountain)
#: shares the SeattleDMR talkgroup layout: https://seattledmr.com/
EXTRA_REPEATERS = [
    ("Seattle/East", "KNW", 440.3375, 445.3375, 2, "SCE"),
]

OUT = ROOT / "src" / "wasds150" / "catalog" / "atd890_dmr.py"
FILENAMES = {
    "digital_repeaters": "Digital-Repeaters-Merged.csv",
    "talkgroups": "Talkgroups-Merged.csv",
    "analog": "Analog-Public-Merged.csv",
}


def _load(source_dir: Path | None) -> dict:
    texts = {}
    for key, url in SEATTLEDMR_FILES.items():
        if source_dir is not None:
            data = (source_dir / FILENAMES[key]).read_bytes()
        else:
            req = urllib.request.Request(url, headers={"User-Agent": "wasds150 snapshot builder"})
            data = urllib.request.urlopen(req, timeout=60).read()
        texts[key] = (data.decode("utf-8-sig", errors="replace"), hashlib.sha256(data).hexdigest().upper())
    return texts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from", dest="source_dir", type=Path, default=None)
    parser.add_argument("--catalog", type=Path, default=ROOT / ".wasds150-home" / "catalog.json")
    args = parser.parse_args()

    texts = _load(args.source_dir)
    repeaters = parse_digital_repeaters(texts["digital_repeaters"][0])
    talkgroups = parse_talkgroups(texts["talkgroups"][0])
    analog = parse_analog(texts["analog"][0])

    coords = None
    if args.catalog.is_file():
        catalog = Catalog.from_dict(json.loads(args.catalog.read_text(encoding="utf-8")))
        coords = coordinate_lookup_from_catalog(catalog)

    tg_ids = {tg.name: tg.tg_id for tg in talkgroups}
    by_code = {r.code: r for r in repeaters}
    for label, code, rx, tx, cc, like in EXTRA_REPEATERS:
        template = by_code.get(like)
        if template is not None and code not in by_code:
            repeaters.append(RepeaterDef(label=label, code=code, rx_mhz=rx, tx_mhz=tx, color_code=cc, slots=dict(template.slots)))
    kept = [r for r in repeaters if r.region != "Outside Washington" and not r.is_hotspot]
    today = datetime.date.today().isoformat()

    lines = [
        '"""Snapshot of the Pacific Northwest DMR network layout for Washington.',
        "",
        "GENERATED by scripts/radios/build_atd890_dmr_snapshot.py - do not edit by hand.",
        "",
        "Source: the SeattleDMR Config Builder files (community-maintained inputs for",
        "K7ABD's Anytone Config Builder covering the PNWDigital and SeattleDMR",
        f"networks), retrieved {today}:",
    ]
    for key, url in SEATTLEDMR_FILES.items():
        lines.append(f"  {url}")
        lines.append(f"    sha256 {texts[key][1]}")
    lines += [
        "",
        "Repeater positions are joined from the WWARA coordination rows in the local",
        "catalog by output frequency and colour code; ``None`` means no unambiguous",
        "match. Talkgroup usage rules: https://pnwdigital.net/talkgroups/",
        '"""',
        "from __future__ import annotations",
        "",
        "from typing import Dict, List, Optional, Tuple",
        "",
        "from wasds150.models.catalog import FavoritesList",
        "",
        f'RETRIEVED = "{today}"',
        "",
        "#: talkgroup column name -> DMR talkgroup id",
        "TALKGROUPS: Dict[str, int] = {",
    ]
    for name in sorted(tg_ids):
        lines.append(f"    {name!r}: {tg_ids[name]},")
    lines += [
        "}",
        "",
        "#: label, code, rx MHz, tx MHz, colour code, lat, lon, {talkgroup column: timeslot}",
        "REPEATERS: List[Tuple[str, str, float, float, int, Optional[float], Optional[float], Dict[str, int]]] = [",
    ]
    for r in sorted(kept, key=lambda r: (r.region, r.rx_mhz)):
        point = coords(r.rx_mhz, r.color_code, site_tokens(r)) if coords else None
        lat = f"{point[0]:.5f}" if point else "None"
        lon = f"{point[1]:.5f}" if point else "None"
        slots = ", ".join(f"{k!r}: {v}" for k, v in sorted(r.slots.items()))
        lines.append(f"    ({r.label!r}, {r.code!r}, {r.rx_mhz:.4f}, {r.tx_mhz:.4f}, {r.color_code}, {lat}, {lon}, {{{slots}}}),")
    lines += [
        "]",
        "",
        "#: zone, name, bandwidth, power, rx MHz, tx MHz, rx tone, tx tone, tx prohibited",
        "ANALOG: List[Tuple[str, str, str, str, float, float, str, str, bool]] = [",
    ]
    for a in analog:
        lines.append(
            f"    ({a.zone!r}, {a.name!r}, {a.bandwidth!r}, {a.power!r}, {a.rx_mhz:.4f}, {a.tx_mhz:.4f}, "
            f"{a.rx_tone!r}, {a.tx_tone!r}, {a.tx_prohibit!r}),"
        )
    lines += [
        "]",
        "",
        "",
        "def favorites() -> List[FavoritesList]:",
        '    """The DMRNET and SEAACS lists built from this snapshot."""',
        "    from wasds150.catalog.atd890_dmr_build import favorites_from_snapshot",
        "",
        "    return favorites_from_snapshot(TALKGROUPS, REPEATERS, ANALOG, RETRIEVED)",
        "",
        "",
        "def favorite() -> FavoritesList:",
        '    """The DMR network list alone (plan-resolution hook)."""',
        "    return favorites()[0]",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(kept)} repeaters, {len(tg_ids)} talkgroups, {len(analog)} analog channels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
