"""Regenerate ``src/wasds150/catalog/brandmeister_snapshot.py`` from the
BrandMeister network's public API.

Usage (from the repository root)::

    .venv\\Scripts\\python.exe scripts\\radios\\build_brandmeister_snapshot.py [--radius 100] [--max-age-days 60]

BrandMeister publishes its device registry and talkgroup directory through
read-only v2 endpoints that need no key (https://api.brandmeister.network/v2):

* ``/device/byMaster/<id>`` for each US master server (3102, 3103, 3104):
  every registered device with its output (``tx``) and input (``rx``)
  frequency, colour code, owner-entered position and last-seen time;
* ``/device/<id>/talkgroup``: the talkgroups the owner has made static, with
  their timeslots;
* ``/talkgroup``: every talkgroup id and name.

Kept: six-digit device ids (repeaters; personal hotspots register under the
owner's seven- or nine-digit DMR id) that run split, report a position within
``--radius`` miles of home and have been seen within ``--max-age-days``. Only
talkgroups the owner has made static are recorded - a dynamic talkgroup is
whatever a user keyed last, so it says nothing about what a channel will hear.
"""
from __future__ import annotations

import argparse
import datetime
import json
import math
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from wasds150 import station  # noqa: E402
from wasds150.plans.template import HOME  # noqa: E402

API = "https://api.brandmeister.network/v2"
US_MASTERS = (3102, 3103, 3104)
OUT = ROOT / "src" / "wasds150" / "catalog" / "brandmeister_snapshot.py"


def _get(path: str):
    req = urllib.request.Request(API + path, headers={"User-Agent": f"wasds150 snapshot builder ({station.CALLSIGN})"})
    with urllib.request.urlopen(req, timeout=120) as response:
        return json.load(response)


def _miles(lat: float, lon: float) -> float:
    p1, p2 = math.radians(HOME[0]), math.radians(lat)
    d = math.sin((p2 - p1) / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(math.radians(lon - HOME[1]) / 2) ** 2
    return 3958.8 * 2 * math.asin(math.sqrt(d))


def _float(value) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--radius", type=float, default=100.0)
    parser.add_argument("--max-age-days", type=int, default=60)
    args = parser.parse_args()

    today = datetime.date.today()
    oldest = today - datetime.timedelta(days=args.max_age_days)
    kept = {}
    for master in US_MASTERS:
        for device in _get(f"/device/byMaster/{master}"):
            bm_id = int(device.get("id") or 0)
            output, input_ = _float(device.get("tx")), _float(device.get("rx"))
            lat, lon = _float(device.get("lat")), _float(device.get("lng"))
            seen = str(device.get("last_seen") or "")
            if not 100_000 <= bm_id <= 999_999 or not output or not input_ or output == input_:
                continue
            if not lat or _miles(lat, lon) > args.radius:
                continue
            if not seen or datetime.date.fromisoformat(seen[:10]) < oldest:
                continue
            kept[bm_id] = device

    names = {int(k): v for k, v in _get("/talkgroup").items() if str(k).isdigit()}
    # Some owners register the callsign as "W7ECG - 312134"; the id is kept separately.
    callsign_by_id = {
        bm_id: re.sub(r"\s*-\s*\d{6}$", "", str(d.get("callsign") or "").strip())
        for bm_id, d in kept.items()
    }
    rows, used = [], set()
    for bm_id in sorted(kept, key=lambda i: _float(kept[i].get("tx"))):
        device = kept[bm_id]
        statics = sorted(
            {(int(t["talkgroup"]), int(t["slot"])) for t in _get(f"/device/{bm_id}/talkgroup")
             if str(t.get("talkgroup", "")).isdigit() and str(t.get("slot", "")) in ("1", "2")},
            key=lambda ts: (ts[1], ts[0]),
        )
        used.update(tg for tg, _slot in statics)
        rows.append((
            bm_id, callsign_by_id[bm_id], str(device.get("city") or "").strip(),
            _float(device.get("tx")), _float(device.get("rx")), int(device.get("colorcode") or 1),
            round(_float(device.get("lat")), 5), round(_float(device.get("lng")), 5),
            str(device.get("last_seen") or "")[:10], tuple(statics),
        ))

    def tg_name(tg: int) -> str:
        if names.get(tg):
            return names[tg]
        if tg in callsign_by_id:
            return f"{callsign_by_id[tg].split('-')[0]} Local"
        return f"TG {tg}"

    lines = [
        '"""Snapshot of the BrandMeister repeaters near home.',
        "",
        "GENERATED by scripts/radios/build_brandmeister_snapshot.py - do not edit by hand.",
        "",
        f"Source: the BrandMeister network's public v2 API, {API}, retrieved {today.isoformat()}:",
        "device registry of the US masters " + ", ".join(str(m) for m in US_MASTERS) + ", each",
        "repeater's static talkgroups, and the talkgroup directory. Repeaters within",
        f"{args.radius:g} miles of home seen in the last {args.max_age_days} days; positions are the",
        "owners' own entries. Talkgroup usage: https://brandmeister.network/",
        '"""',
        "from __future__ import annotations",
        "",
        "from typing import Dict, List, Tuple",
        "",
        "from wasds150.models.catalog import FavoritesList",
        "",
        f'RETRIEVED = "{today.isoformat()}"',
        f"RADIUS_MILES = {args.radius:g}",
        "",
        "#: talkgroup id -> name (BrandMeister's directory, or the owning repeater)",
        "TALKGROUPS: Dict[int, str] = {",
    ]
    lines += [f"    {tg}: {tg_name(tg)!r}," for tg in sorted(used)]
    lines += [
        "}",
        "",
        "#: BrandMeister id, callsign, site, output MHz, input MHz, colour code, lat, lon,",
        "#: last seen, ((static talkgroup, timeslot), ...)",
        "REPEATERS: List[Tuple[int, str, str, float, float, int, float, float, str, Tuple[Tuple[int, int], ...]]] = [",
    ]
    for row in rows:
        bm_id, call, site, output, input_, cc, lat, lon, seen, statics = row
        lines.append(
            f"    ({bm_id}, {call!r}, {site!r}, {output:.4f}, {input_:.4f}, {cc}, {lat:.5f}, {lon:.5f}, "
            f"{seen!r}, {statics!r}),"
        )
    lines += [
        "]",
        "",
        "",
        "def favorites() -> List[FavoritesList]:",
        '    """The BMNET list built from this snapshot."""',
        "    from wasds150.catalog.brandmeister import favorites_from_snapshot",
        "",
        "    return favorites_from_snapshot(TALKGROUPS, REPEATERS, RETRIEVED)",
        "",
        "",
        "def favorite() -> FavoritesList:",
        "    return favorites()[0]",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} repeaters, {len(used)} talkgroups)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
